name: CMake on multiple platforms

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: 
          - ubuntu-20.04
          - windows-2022
          - macos-12
          - macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        echo "platform=${{ runner.os }}-${{ runner.arch }}" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: cmake -B ${{ steps.strings.outputs.build-output-dir }} -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release

    - name: Pack artifact for ${{ matrix.os }} (${{ steps.strings.outputs.platform }})
      if: runner.os != 'Windows'
      run: |
        cd ${{ steps.strings.outputs.build-output-dir }}
        tar -cvf ${{ steps.strings.outputs.platform }}.tar JxrDecApp JxrEncApp

    - name: Pack artifact (windows) ${{ matrix.os }} (${{ steps.strings.outputs.platform }})
      if: runner.os != 'Windows'
      run: |
        cd ${{ steps.strings.outputs.build-output-dir }}/Release
        tar -cvf ${{ steps.strings.outputs.platform }}.tar JxrDecApp.exe JxrEncApp.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.strings.outputs.platform }}
        path: ${{ steps.strings.outputs.build-output-dir }}/${{ steps.strings.outputs.platform }}.tar

  release-binaries:
    runs-on: ubuntu-20.04
    needs: [ build ]
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ${{ github.workspace }}/build

    - name: Publish
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ github.workspace }}/build/*.tar
